### ISSUE TITLE
Are you RandomCat?

### ISSUE THREAD

**Issue by Enerccio** [macagr/operator-tutorial#1]
If so, please contact me :D

**Comment by macagr** [comment]
I'm not.

**Comment by Enerccio** [comment]
Sorry then, must have been same username. Have a nice day!

**Comment by macagr** [comment]
Probably. Thank you! U 2

**Comment by Enerccio** [comment]
Wait... are you sure you are not him? Because you match all other points lol. Like living in Netherlands and having name starting with Random. :D

**Comment by Enerccio** [comment]
On Discord. He left a channel for some issue with another member so I am trying to contact him lol

**Comment by macagr** [comment]
Fine, but I don't see how this is related to me...?

**Comment by Enerccio** [comment]
On discord it says what your original discord name was before swap. His was macagr#

**Comment by macagr** [comment]
If you must, my discord handle is mcanog, not macagr, nor randomcat. And again, this is all a bit weird...

**Comment by Enerccio** [comment]
Nah, that's fine then :) Like I said, bunch of coincidences so I had to make sure :D

**Comment by macagr** [comment]
No problem. Have a nice day.
